### ISSUE TITLE
Cannot get it working

### ISSUE THREAD

**Issue by suntong** [wechaty/puppet-discord#1]
Hi @huan / anyone, 

I cannot get this puppet-discord working, maybe because of something very simple, as both ts-node and esm are new to me.

Can you provide a fully working project that I can just run it please? 

I've done as much as I can for you -- 
https://gist.github.com/suntong/3dc1ec6c3a167340351577c2c5f8e09f

Hopefully it'll be an easy fix for you based on that.   
Here is what I'm getting:

```
$ node -r ts-node/esm index.ts 
internal/modules/cjs/loader.js:948
    throw new ERR_REQUIRE_ESM(filename);
    ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /.../nodejs/wechaty/puppet-discord_test/node_modules/ts-node/esm.mjs
    at Module.load (internal/modules/cjs/loader.js:948:11)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:1244:12)
    at loadPreloadModules (internal/bootstrap/pre_execution.js:467:5)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:70:3)
    at internal/main/run_main_module.js:7:1 {
  code: 'ERR_REQUIRE_ESM'
}
```

BTW, if I run `node index.js`, it'll complain that `Cannot find module .../src/mod.js`, as I can see only `src/mod.ts` there. 

thx for your help.

**Comment by suntong** [comment]
And if I try to do `npm install wechaty-puppet-discord`, I'll get:

```
$ npm install wechaty-puppet-discord
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/wechaty-puppet-discord - Not found
npm ERR! 404 
npm ERR! 404  'wechaty-puppet-discord@*' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by huan** [comment]
Thanks for trying using this nodule!

I will take a look at it and get back to you later.

PS. this nodule is under construction

**Comment by suntong** [comment]
> PS. this nodule is under construction

Yeah, I understand. 

I included my 3rd attempt above only to show that I've tried everything that I could. BTW, this is the first time I'm trying to make things work from git repo too. Last time when I tried, which was the first time that I started to get wechaty working years ago, I failed as well and never tried again. 

I know you've been able to make it work before, so if you could make a working project first, before you moving on to add more features, that'll be really appreciated. thx.

**Comment by huan** [comment]
Thanks for the feedback, I have added a notice in the README and linked it to this issue.
